version: '3'

services:
  zk:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zk
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${MY_IP}:9092"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181

  registry:
    image: confluentinc/cp-schema-registry:5.3.0
    depends_on:
      - kafka
    ports:
      - "8888:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

  consumers:
    image: rubiklabs/hermes:0.0.1
    command: /opt/hermes-consumers/bin/hermes-consumers
    environment:
      HERMES_CONSUMERS_OPTS: "-Dzookeeper.connect.string=zk:2181 -Dkafka.broker.list=kafka:9092 -Dschema.repository.serverUrl=http://registry:8081"
    depends_on:
      - zk
      - kafka

  management:
    image: rubiklabs/hermes:0.0.1
    command: /opt/hermes-management/bin/hermes-management
    ports:
      - "8090:8090"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      HERMES_MANAGEMENT_OPTS: "-Dschema.repository.serverUrl=http://registry:8081"
    depends_on:
      - zk
      - kafka
