---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    # network_mode: host
    ports:
      - "32181:32181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOO_4LW_COMMANDS_WHITELIST=stat,ruok,srvr,mntr
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
      - JVMFLAGS="-Dzookeeper.skipACL=no;zookeeper.sessionRequireClientSASLAuth=true;zookeeper.DigestAuthenticationProvider.superDigest=super:D/InIHSb7yEEbrWz8b9l71RjZJU="
    extra_hosts:
      - "moby:127.0.0.1"
